name: Generate Profile Metrics

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  personality:
    runs-on: ubuntu-latest

    steps:
      - name: Generate 16Personalities metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.16personalities.svg
          token: ${{ github.token }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality,traits
          plugin_16personalities_scores: no
